# Default values for nominatim-docker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eu.gcr.io/indigo-terra-120510/nominatim-docker
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

container:
  port: 8080

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    # kubernetes.io/tls-acme: "true"
  path: /nominatim
  hosts:
    - maps.etecar.ru
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
    cpu: 1000m
    memory: 8Gi
   requests:
    cpu: 500m
    memory: 7Gi

nodeSelector: {}

tolerations:
  - key: "preemptible"
    operator: "Equal"
    value: true
    effect: "NoSchedule"

affinity: {}
